application: watchamovieinahangout

version: 1
runtime: python
api_version: 1

# Set cache duration to 0 for development
default_expiration: "0m"

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: .*
  script: main.py
